apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "invoice-ninja.fullname" . }}
  labels:
    {{- include "invoice-ninja.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      priority: 10
      services:
        - name: {{ include "invoice-ninja.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
        {{- toYaml .Values.ingress.middlewares | nindent 8 }}
      {{- end }}
    {{- if .Values.ingress.authentikOutpost }}
    - match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      kind: Rule
      priority: 15
      services:
        - name: authentik-server
          namespace: authentik
          port: 80
    {{- end }}
