{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoice-ninja.fullname" . }}-mysql
  labels:
    {{- include "invoice-ninja.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  selector:
    {{- include "invoice-ninja.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
{{- end }}
