apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "invoice-ninja.fullname" . }}-public
  labels:
    {{- include "invoice-ninja.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.public.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "invoice-ninja.fullname" . }}-storage
  labels:
    {{- include "invoice-ninja.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}
